server:
  port: 8081  # Gateway ??

spring:
  application:
    name: gateway  # Gateway ??? ??
  main:
    web-application-type: reactive
  cloud:
    gateway:
      routes:
        - id: pickle-pb  # pickle-pb ???? ???
          uri: http://localhost:8002
          predicates:
            - Path=/pickle-pb/**
          filters:
            - AuthenticationFilter

        - id: pickle-customer  # pickle-customer ???? ???
          uri: http://localhost:8003
          predicates:
            - Path=/pickle-customer/**
          filters:
            - AuthenticationFilter

        - id: pickle-common  # pickle-common ???? ???
          uri: http://localhost:8004
          predicates:
            - Path=/pickle-common/**