server:
  port: 8004  # 임의의 가용 포트를 사용 (특정 포트를 원하면 숫자를 설정)

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${COMMON_DATASOURCE_URL}
    username: ${COMMON_DATASOURCE_USERNAME}
    password: ${COMMON_DATASOURCE_PASSWORD}

  application:
    name: pickle-common  # 서비스 이름