server:
  port: 8004  # 임의의 가용 포트를 사용 (특정 포트를 원하면 숫자를 설정)

spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${COMMON_DATASOURCE_URL}
    username: ${COMMON_DATASOURCE_USERNAME}
    password: ${COMMON_DATASOURCE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update

  application:
    name: pickle-common  # 서비스 이름

cloud:
  aws:
    credentials:
      access-key: ${AWS_ACCESS_KEY}
      secret-key: ${AWS_SECRET_KEY}
    region:
      static: ${AWS_REGION}
    s3:
      bucket: ${AWS_S3_BUCKET_NAME}