server:
  port: 8002  # 임의의 가용 포트를 사용 (특정 포트를 원하면 숫자를 설정)

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${PB_DATASOURCE_URL}
    username: ${PB_DATASOURCE_USERNAME}
    password: ${PB_DATASOURCE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update

  application:
    name: pickle-pb  # 서비스 이름


  logging:
    level:
      org:
        springframework:
          security: DEBUG  # Spring Security의 로그 레벨을 DEBUG로 설정