server:
  port: 8002  # 임의의 가용 포트를 사용 (특정 포트를 원하면 숫자를 설정)

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    url: jdbc:mysql://localhost:3306/pickle_pb
    password: '1234'
  jpa:
    hibernate:
      ddl-auto: update

  application:
    name: pickle-pb  # 서비스 이름